version: 2
jobs:
  build:
    docker:
        - image: python:3.6
    working_directory: /app
    steps:
        - checkout

        - restore_cache:
            key: cache--{{ .Branch }}
        - run:
            name: python module install
            command: |
                PYCACHE_DIR=pycache
                mkdir -p ${PYCACHE_DIR}
                XDG_CACHE_HOME=${PYCACHE_DIR} pip install flake8
        - save_cache:
            key: cache--{{ .Branch }}
            paths:
                - pycache

        - run:
            name: Lint
            command: |
                find scripts | grep '\.py$' | xargs flake8
                flake8 ./scripts/eval ./scripts/pp

        - run:
            name: Validate corpus
            command: |
                find corpus -type f | xargs cat | python3 ./scripts/validate.py -i -

